### ISSUE TITLE
Scaleway has ARM servers which do not work with Nanobox

### ISSUE THREAD

**Issue by notxarb** [nanobox-io/nanobox-adapter-libcloud#7]
Filter out ARM servers from what is presented to Nanobox users.

**Comment by danhunsaker** [comment]
Some already were, but there are two architecture tags in their API. `arm` was filtered. `arm64` was not. Deploying the fix now.

**Comment by lakano** [comment]
@danhunsaker  Is this fix should be currently visible on my dashboard please? Because currently I still see the ARM servers.
On « Starter » there is still 6 servers, and 3 of them are ARM64.
On « Baremetal », there is no more ARM server.
On « Intensive », there is still 8 servers, and 4 of them are ARM64.

**Comment by danhunsaker** [comment]
It may take up to 24 hours for the Dashboard to refresh the lists from the provider. Sorry for the inconvenience.
